/**
 * Lessons are the actual teaching material for a topic — not a prompt to paste
 * somewhere else. One markdown file per topic, generated by Claude and stored
 * next to the curriculum so it survives outside this app.
 *
 *   understand/lessons/<module>/<index>-<slug>.md
 */
import fsp from "node:fs/promises";
import path from "node:path";

import { resolvePlaceholders } from "./placeholders";
import { repoRoot } from "./roots";
import type { Topic } from "./types";

export function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

/**
 * Lessons sit beside the module they belong to, inside its track:
 * `<track>/lessons/<module>/<NN>-<slug>.md`. Deriving the path from the module
 * means a new track needs no configuration.
 */
export function lessonFolder(docId: string): string {
  const moduleDir = path.dirname(path.resolve(repoRoot(), docId));
  return path.join(moduleDir, "lessons", path.basename(docId, ".md"));
}

export function lessonPath(docId: string, topic: Topic): string {
  const name = `${String(topic.index).padStart(2, "0")}-${slugify(topic.title)}.md`;
  return path.join(lessonFolder(docId), name);
}

/** Repo-relative path, for display and for the doc index. */
export function lessonId(docId: string, topic: Topic): string {
  return path.relative(repoRoot(), lessonPath(docId, topic));
}

export async function readLesson(
  docId: string,
  topic: Topic,
): Promise<string | null> {
  try {
    const body = await fsp.readFile(lessonPath(docId, topic), "utf8");
    return resolvePlaceholders(body).trim() || null;
  } catch {
    return null;
  }
}

export async function writeLesson(
  docId: string,
  topic: Topic,
  body: string,
): Promise<string> {
  const file = lessonPath(docId, topic);
  await fsp.mkdir(path.dirname(file), { recursive: true });
  await fsp.writeFile(file, body.endsWith("\n") ? body : body + "\n", "utf8");
  return path.relative(repoRoot(), file);
}

/**
 * The single prompt used both by the in-app "Teach me this" button and by bulk
 * generation, so every lesson comes out in the same shape.
 */
export function lessonPrompt(input: {
  moduleTitle: string;
  moduleGoal: string;
  topic: Topic;
  /** Background from the track's track.json, so each subject teaches in its own world. */
  trackContext: string;
  trackName: string;
}): string {
  const { moduleTitle, moduleGoal, topic, trackContext, trackName } = input;
  // A topic that cites audit findings is taught against one real environment;
  // anything else is taught so the same lesson works for any reader.
  const audited = topic.audit.length > 0;
  return `You are writing a self-contained lesson for a study guide. Write ONLY the lesson, in markdown. No preamble, no sign-off, no "here is your lesson".

${trackContext || `The learner is working through a ${trackName} curriculum.`}

TRACK: ${trackName}
MODULE: ${moduleTitle}
MODULE GOAL: ${moduleGoal || "(none stated)"}
TOPIC: ${topic.title}
CURRICULUM'S ONE-LINE SUMMARY: ${topic.description || "(none)"}
${topic.audit.length ? `AUDIT ITEMS THIS TOPIC EXPLAINS: ${topic.audit.join(", ")}` : ""}
${topic.see ? `A READ-ONLY COMMAND THAT SHOWS THIS IN OUR SETUP: ${topic.see}` : ""}

Teach this topic from zero, with real-world examples and plain-English explanation. Define
every term the first time you use it. Assume no prior infrastructure knowledge, but never
talk down — the reader is a working engineer.

Use exactly these sections, in this order:

## In one line
One sentence a non-engineer would understand.

## The everyday version
A concrete real-world analogy from ordinary life (post, buildings, phone numbers, keys,
office passes). Two short paragraphs at most. Make it stick.

## How it actually works
The real mechanism, step by step. Use a small numbered walkthrough or a short table where
it helps. Show real commands and realistic values. ${
    audited
      ? "Not placeholders."
      : "Where the environment above is described with {{env:NAME}} placeholders, keep them exactly as written — never invent a cluster, account or company name."
  }

${
  audited
    ? `## In our setup
Tie it to the actual environment described above. Be specific and use real names, real
numbers and real commands from it. If the topic has a command that shows it, include the command and describe what
the output will look like and how to read it.

## Why the audit cares
Explain what ${topic.audit.join(" and ")} actually mean in light of this topic, what an attacker does with it, and what the fix direction is.`
    : `## In your setup
How to see this on the reader's own cluster. Give the exact read-only command, say what the
output looks like and how to read it. Refer to the environment only through the {{env:NAME}}
placeholders used above, so the lesson is true for whoever reads it.

## Why it matters
What goes wrong when this is misunderstood — a short, realistic failure story — what it
costs, and what good looks like.`
}

## Check yourself
Three questions the reader should be able to answer out loud without looking. Then, after
each question, a one-line answer in italics so they can check themselves.

Rules:
- 600 to 900 words total.
- Short paragraphs. No wall of text.
- Plain English. Every acronym expanded on first use.
- Concrete numbers, real command output shapes, real failure stories where they fit.
- Do not tell the reader to go ask someone else. This lesson IS the resource.`;
}
