#!/usr/bin/env node
/**
 * Writes the missing lesson for every topic in a track, in parallel.
 *
 *   npm run dev                      # in another terminal
 *   npm run lessons                  # every track
 *   npm run lessons -- kubernetes-basics
 *   npm run lessons -- kubernetes-basics --concurrency 6 --dry
 *
 * Each lesson is generated by the app's own endpoint, which shells out to the
 * Claude Code CLI, so this needs no API key — just a logged-in `claude`.
 */
const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const at = args.indexOf(`--${name}`);
  return at === -1 ? fallback : args[at + 1];
};
const BASE = flag("base", "http://localhost:3000");
const CONCURRENCY = Number(flag("concurrency", 4));
const DRY = args.includes("--dry");
const track = args.find((a) => !a.startsWith("--") && args[args.indexOf(a) - 1] !== "--base" && args[args.indexOf(a) - 1] !== "--concurrency");

async function main() {
  let index;
  try {
    index = await (await fetch(`${BASE}/api/understand`)).json();
  } catch {
    console.error(`Could not reach ${BASE}. Is \`npm run dev\` running?`);
    process.exit(1);
  }

  const trackIds = index.collections.filter((c) => c.kind === "curriculum").map((c) => c.id);
  const wanted = track ? [track] : trackIds;
  for (const id of wanted) {
    if (!trackIds.includes(id)) {
      console.error(`Unknown track "${id}". Available: ${trackIds.join(", ")}`);
      process.exit(1);
    }
  }

  // A track README's checklist is its plan — one line per module — not topics.
  const modules = index.docs.filter(
    (d) => wanted.includes(d.collection) && d.topicCount > 0 && !/(^|\/)README\.md$/i.test(d.id),
  );
  const jobs = [];
  for (const mod of modules) {
    const detail = await (
      await fetch(`${BASE}/api/understand/doc?id=${encodeURIComponent(mod.id)}`)
    ).json();
    for (const topic of detail.topics) {
      if (!topic.lesson) jobs.push({ id: mod.id, index: topic.index, title: topic.title, module: mod.title });
    }
  }

  if (!jobs.length) {
    console.log("Every topic already has a lesson.");
    return;
  }
  console.log(`${jobs.length} lessons to write across ${modules.length} modules, ${CONCURRENCY} at a time.`);
  if (DRY) {
    for (const job of jobs) console.log(`  would write: ${job.module} → ${job.title}`);
    return;
  }

  let done = 0;
  let failed = 0;
  const queue = [...jobs];
  async function worker() {
    for (let job = queue.shift(); job; job = queue.shift()) {
      const started = Date.now();
      try {
        const res = await fetch(`${BASE}/api/understand/lesson`, {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ id: job.id, index: job.index }),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error ?? `HTTP ${res.status}`);
        done++;
        const secs = Math.round((Date.now() - started) / 1000);
        console.log(`  ✓ [${done + failed}/${jobs.length}] ${job.title} (${secs}s)`);
      } catch (cause) {
        failed++;
        console.log(`  ✗ [${done + failed}/${jobs.length}] ${job.title} — ${cause.message}`);
      }
    }
  }
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  console.log(`\nWrote ${done}, failed ${failed}.`);
  process.exit(failed ? 1 : 0);
}

main();
